#logging:
#  level:
#    org.apache.shiro: DEBUG

server:
#  port: 9000

spring:

#  aop:
#    proxy-target-class: true # not working

  jpa:
#    generate-ddl: true
    show-sql: true

#    hibernate:
#      ddl-auto: create # none # validate # update # create-drop

  datasource:
    url:      jdbc:mysql://localhost/hly?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=CST
    username: hly
    password: hly
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    rest:
      basePath: /api/data
#shiro:
#  web:
#    enabled: false

