#logging:
#  level:
#    org.apache.shiro: DEBUG

server:
  port: 8081

spring:

#  aop:
#    proxy-target-class: true # not working

  jpa:
#    generate-ddl: true
    show-sql: true

#    hibernate:
#      ddl-auto: create # none # validate # update # create-drop

  datasource:
    url:      jdbc:mysql://127.0.0.1/hly?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&noAccessToProcedureBodies=true&serverTimezone=CST
    username: hly
    password: hly
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    rest:
      basePath: /api/data

  freemarker:
    cache: false
    template_update_delay: 0
#shiro:
#  web:
#    enabled: false

