#logging:
#  level:
#    org.apache.shiro: DEBUG

server:
  port: 8081

spring:

  jackson:
    date-format: yyyy-MM-dd
#      HH:mm:ss

#  aop:
#    proxy-target-class: true # not working

  jpa:
#    generate-ddl: true
    show-sql: true

#    hibernate:
#      ddl-auto: create-drop #update #create # none # validate # update # create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  datasource:
    url:      jdbc:mysql://127.0.0.1/hly?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&noAccessToProcedureBodies=true&serverTimezone=CST
    username: hly
    password: hly
    driver-class-name: com.mysql.cj.jdbc.Driver

#  https://docs.spring.io/spring-data/rest/docs/current/reference/html/#_changing_other_spring_data_rest_properties
  data:
    rest:
      basePath: /api/data
      defaultPageSize: 200

  freemarker:
    cache: false
    template_update_delay: 0
#shiro:
#  web:
#    enabled: false

#hibernate:
#  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    storage_engine: innodb
